#!/bin/bash

# Claude Agent Swarm 蜂群演示脚本
# 演示如何使用 3 个 Agent 并行开发 TUI 增强功能

set -e

echo "════════════════════════════════════════════════════════════"
echo "  🐝 Claude Agent Swarm 蜂群演示"
echo "════════════════════════════════════════════════════════════"
echo ""
echo "📋 已准备 4 个并行任务："
echo "  1. 任务过滤功能"
echo "  2. Agent 性能统计"
echo "  3. 帮助面板"
echo "  4. 主题切换"
echo ""
echo "💡 演示步骤："
echo ""

# 步骤 1
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "第 1 步：查看任务队列"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
./swarm status
echo ""
read -p "按 Enter 继续..."
echo ""

# 步骤 2
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "第 2 步：启动 3 个 Agent 蜂群"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "将在 tmux 会话中启动 3 个 Claude Agent..."
echo "每个 Agent 会自动领取任务并开始工作"
echo ""
echo "命令：./swarm start --agents 3"
echo ""
echo "⚠️  注意：启动后会进入后台运行"
echo "   您将看到："
echo "   - Agent 在独立 tmux 窗格中工作"
echo "   - 自动任务分发"
echo "   - 智能调度和监控"
echo ""
read -p "按 Enter 启动蜂群（Ctrl+C 取消）..."
echo ""

# 在后台启动 swarm（实际使用时）
echo "💡 提示：使用以下命令在终端 1 启动："
echo "   ./swarm start --agents 3"
echo ""
echo "   然后在终端 2 运行："
echo "   ./swarm monitor"
echo ""

# 步骤 3
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "第 3 步：实时监控（TUI Monitor）"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "启动 TUI 可视化监控面板查看实时进度："
echo ""
echo "  📋 任务列表        👥 Agent 网格        📝 日志查看器"
echo "  ┌─────────────┐   ┌─────────────┐   ┌─────────────┐"
echo "  │ ○ task-001  │   │ agent-0 ●   │   │ agent-0     │"
echo "  │ ● task-002  │   │ agent-1 ●   │   │ Working on  │"
echo "  │ ○ task-003  │   │ agent-2 ●   │   │ task-002... │"
echo "  │ ○ task-004  │   │             │   │             │"
echo "  └─────────────┘   └─────────────┘   └─────────────┘"
echo ""
echo "  ⌨️  Tab: 切换面板 | j/k: 导航 | q: 退出"
echo ""
echo "命令：./swarm monitor"
echo ""

# 步骤 4
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "预期行为"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "✨ 蜂群工作流程："
echo ""
echo "1. Agent-0 领取 task-filter-001（任务过滤）"
echo "   → 修改 tasklist.go"
echo "   → 修改 dashboard.go"
echo "   → 运行测试验证"
echo "   → 优化性能"
echo "   → 提交完成 ✓"
echo ""
echo "2. Agent-1 领取 task-stats-002（性能统计）"
echo "   → 创建 agentstats.go"
echo "   → 集成到 dashboard"
echo "   → 添加样式"
echo "   → 测试和优化"
echo "   → 提交完成 ✓"
echo ""
echo "3. Agent-2 领取 task-help-003（帮助面板）"
echo "   → 创建 helppanel.go"
echo "   → 实现模态框"
echo "   → 集成快捷键处理"
echo "   → 调试验证"
echo "   → 提交完成 ✓"
echo ""
echo "4. 当 Agent 完成任务后，自动领取 task-theme-004"
echo "   → 实现主题系统"
echo "   → 应用到所有组件"
echo "   → 测试切换"
echo "   → 性能优化"
echo "   → 提交完成 ✓"
echo ""
echo "🎯 预计时间："
echo "   - 串行执行：5-7 小时"
echo "   - 3个Agent并行：~2 小时"
echo "   - 效率提升：60-70%"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "监控要点"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "在 TUI Monitor 中观察："
echo ""
echo "✓ 任务状态变化："
echo "  pending → in_progress → completed"
echo ""
echo "✓ Agent 状态："
echo "  idle（灰色）→ working（蓝色）→ waiting_confirm（黄色）→ idle"
echo ""
echo "✓ 日志输出："
echo "  实时显示 Agent 的工作进度和输出"
echo ""
echo "✓ 自动处理："
echo "  - 确认提示自动响应"
echo "  - 错误自动检测"
echo "  - 卡住状态自动识别"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "完整命令参考"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "# 终端 1：启动蜂群"
echo "./swarm start --agents 3"
echo ""
echo "# 终端 2：监控进度"
echo "./swarm monitor"
echo ""
echo "# 终端 3：查看 tmux 原始输出（可选）"
echo "tmux attach -t claude-swarm"
echo "# 退出：Ctrl+B 然后 D"
echo ""
echo "# 其他命令"
echo "./swarm status          # 查看状态"
echo "./swarm add-task \"...\"  # 添加新任务"
echo "./swarm stop            # 停止集群"
echo ""

echo "════════════════════════════════════════════════════════════"
echo "演示准备完成！"
echo "════════════════════════════════════════════════════════════"
echo ""
echo "📌 当前状态："
echo "  ✓ 任务队列已创建（4个任务）"
echo "  ✓ TUI Monitor 已就绪"
echo "  ✓ 系统已编译"
echo ""
echo "🚀 开始使用："
echo "  1. 新开终端 1：./swarm start --agents 3"
echo "  2. 新开终端 2：./swarm monitor"
echo "  3. 观察 Agent 自动工作"
echo ""
echo "💡 提示："
echo "  - 第一次启动 Agent 可能需要几秒初始化"
echo "  - 使用 Tab 键在 Monitor 面板间切换"
echo "  - 按 q 退出 Monitor（不影响 Agent 工作）"
echo ""
